import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, expect, it, vi } from 'vitest';
import App from './App';
import { api, type Container } from './api';
import { installSnapshotStreams } from './test/snapshotStreams';
vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), api: { getEnvironment: vi.fn(), listContainers: vi.fn(), getRecentLogs: vi.fn(), startLogStream: vi.fn(), readLogStream: vi.fn(), stopLogStream: vi.fn(), getContainerStats: vi.fn(), mutateContainer: vi.fn(), mutateContainers: vi.fn() } }));
const mock = vi.mocked(api);
const row = (name: string, project: string | null, service: string | null, state = 'running'): Container => ({ handle: name, fullId: name.padEnd(64, 'a'), shortId: name.padEnd(12, 'a'), name, image: 'fixture', state, health: null, ports: [], composeProject: project, composeService: service, createdAt: '' });
const rows = [row('zulu', 'beta', 'worker'), row('redis', 'alpha', 'redis', 'exited'), row('api', 'alpha', 'backend'), row('single', null, null)];
beforeEach(() => {
  vi.resetAllMocks(); installSnapshotStreams(mock);
  localStorage.setItem('docker2u.preferences.v1', JSON.stringify({ theme: 'dark', language: 'ko' }));
  mock.getEnvironment.mockResolvedValue({ status: 'ready', sessionId: 'one', contextName: 'fixture', endpoint: 'unix:///fixture.sock', dockerPath: '/fixture/docker', dockerConfigPath: '/fixture/config', clientVersion: '1', serverVersion: '1', apiVersion: '1', engineId: 'one', osType: 'linux', architecture: 'arm64', mutationAllowed: true, error: null, diagnostics: [] });
  mock.listContainers.mockResolvedValue({ sessionId: 'one', generation: 1, containers: rows, refreshedAt: '2026-09-07T00:00:00Z', stale: false });
  mock.getRecentLogs.mockImplementation(async (sessionId, handle) => ({ sessionId, handle, generation: 1, text: 'ready', byteCount: 5, truncated: false, command: 'fixture', stderr: '' }));
  mock.getContainerStats.mockImplementation(async (sessionId, generation, handles) => ({ sessionId, generation, sampledAt: '2026-09-07T01:02:03Z', error: null, items: handles.map(handle => ({ handle, fullId: rows.find(item => item.handle === handle)!.fullId, available: true, cpuPercent: handle === 'api' ? 0 : 125.5, memoryUsage: '64MiB / 2GiB', memoryPercent: 3.125 })) }));
});
it('groups visible rows and scopes project filtering, service search, checkboxes and hidden detail selection', async () => {
  const user = userEvent.setup(); render(<App />); await screen.findByRole('button', { name: 'api 상세' });
  const table = screen.getByRole('table', { name: '컨테이너 목록' });
  expect(within(table).getAllByRole('heading').map(heading => heading.closest('tr')?.textContent)).toEqual(['alpha2프로젝트 보기', 'beta1프로젝트 보기', '프로젝트 없음1프로젝트 보기']);
  await user.click(screen.getByRole('button', { name: 'zulu 상세' }));
  await user.click(screen.getByRole('checkbox', { name: '보이는 컨테이너 전체 선택' }));
  await user.selectOptions(screen.getByRole('combobox', { name: '프로젝트' }), JSON.stringify(['project', 'alpha']));
  expect(screen.queryByRole('button', { name: 'zulu 상세' })).not.toBeInTheDocument();
  expect(screen.queryByText('4개 선택')).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: '로그 조회' })).not.toBeInTheDocument();
  await user.type(screen.getByRole('textbox', { name: '컨테이너 검색' }), 'backend');
  expect(within(table).getByRole('heading', { name: 'alpha' }).closest('tr')).toHaveTextContent('alpha1');
  await user.click(screen.getByRole('checkbox', { name: '보이는 컨테이너 전체 선택' }));
  expect(screen.getByRole('checkbox', { name: 'api 작업 대상으로 선택' })).toBeChecked();
  expect(mock.mutateContainers).not.toHaveBeenCalled();
});
it('uses the same CPU and memory sample in list and detail, including 0 and values above 100', async () => {
  const user = userEvent.setup(); render(<App />);
  const zulu = await screen.findByRole('button', { name: 'zulu 상세' });
  const zuluRow = within(zulu.closest('tr')!);
  await waitFor(() => expect(zuluRow.getByRole('cell', { name: '125.50%' })).toBeVisible());
  expect(zuluRow.getByRole('cell', { name: '64MiB' })).toBeVisible();
  await user.click(zulu);
  const information = screen.getByText('컨테이너 정보').closest('details')!;
  expect(information).not.toHaveAttribute('open');
  expect(within(information).getByText('125.50%')).not.toBeVisible();
  await user.click(within(information).getByText('컨테이너 정보'));
  const detail = within(information).getByRole('region', { name: '자원 사용량' });
  expect(detail).toHaveTextContent(zuluRow.getByRole('cell', { name: '125.50%' }).textContent!);
  expect(detail).toHaveTextContent('64MiB / 2GiB');
  await user.click(screen.getByRole('button', { name: 'api 상세' }));
  expect(detail).toHaveTextContent('0.00%');
  expect(within(screen.getByRole('button', { name: 'api 상세' }).closest('tr')!).getByRole('cell', { name: '0.00%' })).toBeVisible();
  const stoppedCells = within(screen.getByRole('button', { name: 'redis 상세' }).closest('tr')!).getAllByRole('cell');
  expect(stoppedCells[3]).toHaveTextContent('—');
  expect(stoppedCells[4]).toHaveTextContent('—');
  expect(mock.getContainerStats).toHaveBeenCalledExactlyOnceWith('one', 1, ['api', 'zulu', 'single']);
});
it('resizes the log pane with the keyboard without replacing the selected row, sample or live stream', async () => {
  let sequence = 0;
  mock.readLogStream.mockImplementation(async (sessionId, streamId) => ({ sessionId, streamId,
    sequence: ++sequence, text: sequence === 1 ? 'ready\n' : '', truncated: false, terminal: false, error: null }));
  const user = userEvent.setup(); render(<App />);
  const selected = await screen.findByRole('button', { name: 'api 상세' });
  const selectedRow = within(selected.closest('tr')!);
  await waitFor(() => expect(selectedRow.getByRole('cell', { name: '0.00%' })).toBeVisible());
  const logs = screen.getByLabelText('최근 로그 내용');
  await waitFor(() => expect(logs).toHaveTextContent('ready'));
  expect(mock.startLogStream).toHaveBeenCalledExactlyOnceWith('one', 1, 'api');
  const separator = screen.getByRole('separator', { name: '로그 패널 높이 조절' });
  const initialHeight = Number(separator.getAttribute('aria-valuenow'));
  separator.focus();
  await user.keyboard('{ArrowUp}');
  expect(separator).toHaveAttribute('aria-valuenow', String(initialHeight + 20));
  await user.keyboard('{Home}');
  expect(separator).toHaveAttribute('aria-valuenow', separator.getAttribute('aria-valuemin'));
  await user.keyboard('{End}');
  expect(separator).toHaveAttribute('aria-valuenow', separator.getAttribute('aria-valuemax'));
  expect(separator).toHaveFocus();
  expect(screen.getByRole('button', { name: 'api 상세' })).toBe(selected);
  expect(selected).toHaveAttribute('aria-current', 'true');
  expect(selectedRow.getByRole('cell', { name: '0.00%' })).toBeVisible();
  expect(selectedRow.getByRole('cell', { name: '64MiB' })).toBeVisible();
  expect(screen.getByLabelText('최근 로그 내용')).toBe(logs);
  expect(logs).toHaveTextContent('ready');
  expect(mock.startLogStream).toHaveBeenCalledTimes(1);
  expect(mock.stopLogStream).not.toHaveBeenCalled();
  expect(mock.getContainerStats).toHaveBeenCalledExactlyOnceWith('one', 1, ['api', 'zulu', 'single']);
  expect(mock.listContainers).toHaveBeenCalledTimes(1);
  expect(mock.getEnvironment).toHaveBeenCalledTimes(1);
  expect(mock.mutateContainer).not.toHaveBeenCalled();
  expect(mock.mutateContainers).not.toHaveBeenCalled();
});
it('keeps keyboard navigation in the grouped visual order', async () => {
  const user = userEvent.setup(); render(<App />); const first = await screen.findByRole('button', { name: 'api 상세' }); first.focus();
  await user.keyboard('{ArrowDown}'); expect(screen.getByRole('button', { name: 'redis 상세' })).toHaveFocus();
  await user.keyboard('{End}'); expect(screen.getByRole('button', { name: 'single 상세' })).toHaveFocus();
});
it.each([JSON.stringify(['project', 'beta']), 'none'])('retains an empty project scope %s when accepting the next inventory', async value => {
  const user = userEvent.setup(); render(<App />); await screen.findByRole('button', { name: 'api 상세' });
  const project = screen.getByRole('combobox', { name: '프로젝트' }); await user.selectOptions(project, value);
  mock.listContainers.mockResolvedValueOnce({ sessionId: 'one', generation: 2, containers: rows.filter(item => item.composeProject === 'alpha'), refreshedAt: '2026-09-07T00:00:01Z', stale: false });
  await user.click(screen.getByRole('button', { name: '새로고침' }));
  await waitFor(() => expect(project).toHaveValue(value));
  expect(screen.queryByRole('button', { name: 'api 상세' })).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'redis 상세' })).not.toBeInTheDocument();
});
