import { act, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, expect, it, vi } from 'vitest';
import App from './App';
import { api, type Container, type ContainerDetails } from './api';
import { installSnapshotStreams } from './test/snapshotStreams';
import { containerDetailsFixture } from './test/containerDetailsFixture';
vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), api: { getEnvironment: vi.fn(), listContainers: vi.fn(), getRecentLogs: vi.fn(), startLogStream: vi.fn(), readLogStream: vi.fn(), stopLogStream: vi.fn(), getContainerStats: vi.fn(), getContainerDetails: vi.fn(), mutateContainer: vi.fn(), mutateContainers: vi.fn() } }));
const mock = vi.mocked(api);
const row = (name: string, project: string | null, service: string | null, state = 'running'): Container => ({ handle: name, fullId: name.padEnd(64, 'a'), shortId: name.padEnd(12, 'a'), name, image: 'fixture', state, health: null, healthConfigured: null, ports: [], composeProject: project, composeService: service, createdAt: '' });
const rows = [row('zulu', 'beta', 'worker'), row('redis', 'alpha', 'redis', 'exited'), row('api', 'alpha', 'backend'), row('single', null, null)];
beforeEach(() => {
  vi.resetAllMocks(); installSnapshotStreams(mock);
  localStorage.setItem('docker2u.preferences.v1', JSON.stringify({ theme: 'dark', language: 'ko' }));
  mock.getEnvironment.mockResolvedValue({ status: 'ready', sessionId: 'one', contextName: 'fixture', endpoint: 'unix:///fixture.sock', dockerPath: '/fixture/docker', dockerConfigPath: '/fixture/config', clientVersion: '1', serverVersion: '1', apiVersion: '1', engineId: 'one', osType: 'linux', architecture: 'arm64', mutationAllowed: true, error: null, diagnostics: [] });
  mock.listContainers.mockResolvedValue({ sessionId: 'one', generation: 1, containers: rows, refreshedAt: '2026-09-07T00:00:00Z', stale: false });
  mock.getRecentLogs.mockImplementation(async (sessionId, handle) => ({ sessionId, handle, generation: 1, text: 'ready', byteCount: 5, truncated: false, command: 'fixture', stderr: '' }));
  mock.getContainerStats.mockImplementation(async (sessionId, generation, handles) => ({ sessionId, generation, sampledAt: '2026-09-07T01:02:03Z', error: null, items: handles.map(handle => ({ handle, fullId: rows.find(item => item.handle === handle)!.fullId, available: true, cpuPercent: handle === 'api' ? 0 : 125.5, memoryUsage: '64MiB / 2GiB', memoryPercent: 3.125 })) }));
  mock.getContainerDetails.mockImplementation(async (sessionId, generation, handle) => containerDetailsFixture(rows.find(item => item.handle === handle)!, { sessionId, generation, containers: rows, refreshedAt: '', stale: false }));
});
it('separates project navigation, filtered inventory and checked actions', async () => {
  const user = userEvent.setup(); render(<App />); await screen.findByRole('treeitem', { name: 'api 상세' });
  const tree = screen.getByRole('tree', { name: '컨테이너 목록' });
  expect(screen.queryByRole('combobox', { name: '프로젝트' })).not.toBeInTheDocument();
  await user.click(screen.getByRole('treeitem', { name: 'zulu 상세' }));
  await user.click(screen.getByRole('checkbox', { name: '보이는 컨테이너 전체 선택' }));
  await user.click(within(tree).getByRole('treeitem', { name: 'alpha 프로젝트' }));
  expect(screen.getByRole('heading', { name: '프로젝트 · alpha' })).toBeVisible();
  expect(screen.getByText('4개 선택')).toBeVisible();
  expect(screen.getByRole('treeitem', { name: 'zulu 상세' })).toBeVisible();
  await user.click(screen.getByRole('treeitem', { name: 'zulu 상세' }));
  await user.type(screen.getByRole('textbox', { name: '컨테이너 검색' }), 'backend');
  expect(screen.queryByRole('treeitem', { name: 'zulu 상세' })).not.toBeInTheDocument();
  expect(screen.getByRole('heading', { name: 'zulu' })).toBeVisible();
  expect(screen.getByText('현재 대상이 검색 또는 상태 필터에 가려져 있습니다.')).toBeVisible();
  expect(screen.getByRole('checkbox', { name: 'api 작업 대상으로 선택' })).toBeChecked();
  expect(screen.getByText('1개 선택')).toBeVisible();
  expect(mock.mutateContainers).not.toHaveBeenCalled();
});
it('uses the same CPU and memory sample in list and detail, including 0 and values above 100', async () => {
  const user = userEvent.setup(); render(<App />);
  const zulu = await screen.findByRole('treeitem', { name: 'zulu 상세' });
  const zuluRow = within(zulu.closest('.container-list-item')!);
  await waitFor(() => expect(zuluRow.getByText('125.50%', { exact: false })).toBeVisible());
  expect(zuluRow.getByText('64MiB', { exact: false })).toBeVisible();
  await user.click(zulu);
  expect(screen.queryByRole('region', { name: '컨테이너 정보' })).not.toBeInTheDocument();
  await user.click(screen.getByRole('tab', { name: '접속 정보' }));
  const information = screen.getByRole('region', { name: '컨테이너 정보' });
  const detail = within(information).getByRole('region', { name: '자원 사용량' });
  expect(detail).toHaveTextContent(zuluRow.getByText('125.50%', { exact: false }).textContent!);
  expect(detail).toHaveTextContent('64MiB / 2GiB');
  await user.click(screen.getByRole('treeitem', { name: 'api 상세' }));
  expect(screen.queryByRole('region', { name: '컨테이너 정보' })).not.toBeInTheDocument();
  await user.click(screen.getByRole('tab', { name: '접속 정보' }));
  expect(within(screen.getByRole('region', { name: '컨테이너 정보' })).getByRole('region', { name: '자원 사용량' })).toHaveTextContent('0.00%');
  expect(within(screen.getByRole('treeitem', { name: 'api 상세' }).closest('.container-list-item')!).getByText('0.00%', { exact: false })).toBeVisible();
  const stoppedRow = screen.getByRole('treeitem', { name: 'redis 상세' }).closest('.container-list-item')!;
  expect(stoppedRow.querySelector('.container-cpu-value')).toHaveTextContent('—');
  expect(stoppedRow.querySelector('.container-memory-value')).toHaveTextContent('—');
  expect(mock.getContainerStats).toHaveBeenCalledExactlyOnceWith('one', 1, ['api', 'zulu', 'single']);
});
it('keeps list information and full ID copying available while connection details are loading or fail', async () => {
  let reject!: (reason: unknown) => void;
  mock.getContainerDetails.mockReturnValueOnce(new Promise<ContainerDetails>((_resolve, fail) => { reject = fail; }));
  const user = userEvent.setup();
  const clipboard = vi.spyOn(navigator.clipboard, 'writeText').mockResolvedValue(undefined);
  render(<App />); await screen.findByRole('treeitem', { name: 'api 상세' });
  await user.click(screen.getByRole('tab', { name: '접속 정보' }));
  const information = screen.getByRole('region', { name: '컨테이너 정보' });
  expect(screen.getByText('상세 정보를 조회하고 있습니다.')).toBeVisible();
  expect(within(information).getByText(rows[2]!.fullId)).toBeVisible();
  expect(within(information).getByText('fixture')).toBeVisible();
  expect(within(information).getByText('alpha')).toBeVisible();
  expect(within(information).getByText('backend')).toBeVisible();
  await act(async () => reject({ code: 'TimedOut', message: 'Details timed out' }));
  expect(await screen.findByText('상세 정보를 조회하지 못했습니다.')).toBeVisible();
  expect(screen.getByRole('region', { name: '컨테이너 정보' })).toBe(information);
  await user.click(within(information).getByRole('button', { name: '전체 ID 복사' }));
  expect(clipboard).toHaveBeenCalledExactlyOnceWith(rows[2]!.fullId);
});
it('resizes navigation with the keyboard without replacing the selected row, sample or live stream', async () => {
  let sequence = 0;
  mock.readLogStream.mockImplementation(async (sessionId, streamId) => ({ sessionId, streamId,
    sequence: ++sequence, text: sequence === 1 ? 'ready\n' : '', truncated: false, terminal: false, error: null }));
  const user = userEvent.setup(); render(<App />);
  const selected = await screen.findByRole('treeitem', { name: 'api 상세' });
  const selectedRow = within(selected.closest('.container-list-item')!);
  await waitFor(() => expect(selectedRow.getByText('0.00%', { exact: false })).toBeVisible());
  const logs = screen.getByLabelText('최근 로그 내용');
  await waitFor(() => expect(logs).toHaveTextContent('ready'));
  expect(mock.startLogStream).toHaveBeenCalledExactlyOnceWith('one', 1, 'api');
  const separator = screen.getByRole('separator', { name: '탐색 영역 너비 조절' });
  const initialHeight = Number(separator.getAttribute('aria-valuenow'));
  separator.focus();
  await user.keyboard('{ArrowRight}');
  expect(separator).toHaveAttribute('aria-valuenow', String(initialHeight + 20));
  await user.keyboard('{Home}');
  expect(separator).toHaveAttribute('aria-valuenow', separator.getAttribute('aria-valuemin'));
  await user.keyboard('{End}');
  expect(separator).toHaveAttribute('aria-valuenow', separator.getAttribute('aria-valuemax'));
  expect(separator).toHaveFocus();
  expect(screen.getByRole('treeitem', { name: 'api 상세' })).toBe(selected);
  expect(selected).toHaveAttribute('aria-selected', 'true');
  expect(selectedRow.getByText('0.00%', { exact: false })).toBeVisible();
  expect(selectedRow.getByText('64MiB', { exact: false })).toBeVisible();
  expect(screen.getByLabelText('최근 로그 내용')).toBe(logs);
  expect(logs).toHaveTextContent('ready');
  expect(mock.startLogStream).toHaveBeenCalledTimes(1);
  expect(mock.stopLogStream).not.toHaveBeenCalled();
  expect(mock.getContainerStats).toHaveBeenCalledExactlyOnceWith('one', 1, ['api', 'zulu', 'single']);
  expect(mock.listContainers).toHaveBeenCalledTimes(1);
  expect(mock.getEnvironment).toHaveBeenCalledTimes(1);
  expect(mock.mutateContainer).not.toHaveBeenCalled();
  expect(mock.mutateContainers).not.toHaveBeenCalled();
});
it('keeps keyboard navigation in the grouped visual order', async () => {
  const user = userEvent.setup(); render(<App />); const first = await screen.findByRole('treeitem', { name: 'api 상세' }); first.focus();
  await user.keyboard('{ArrowDown}'); expect(screen.getByRole('treeitem', { name: 'redis 상세' })).toHaveFocus();
  await user.keyboard('{End}'); expect(screen.getByRole('treeitem', { name: 'single 상세' })).toHaveFocus();
});
it('retains selected project context when its last container disappears', async () => {
  const user = userEvent.setup(); render(<App />); await screen.findByRole('treeitem', { name: 'api 상세' });
  await user.click(within(screen.getByRole('tree')).getByRole('treeitem', { name: 'beta 프로젝트' }));
  mock.listContainers.mockResolvedValueOnce({ sessionId: 'one', generation: 2, containers: rows.filter(item => item.composeProject === 'alpha'), refreshedAt: '2026-09-07T00:00:01Z', stale: false });
  await user.click(screen.getByRole('button', { name: '새로고침' }));
  await waitFor(() => expect(screen.queryByRole('treeitem', { name: 'zulu 상세' })).not.toBeInTheDocument());
  expect(screen.getByRole('heading', { name: '프로젝트 · beta' })).toBeVisible();
  expect(screen.getByRole('treeitem', { name: 'api 상세' })).toBeVisible();
});

it('remembers each target tab and restores the project after container removal', async () => {
  const user = userEvent.setup(); render(<App />); await screen.findByRole('treeitem', { name: 'api 상세' });
  await user.click(screen.getByRole('tab', { name: '이력' }));
  await user.click(within(screen.getByRole('tree')).getByRole('treeitem', { name: 'alpha 프로젝트' }));
  expect(screen.getByRole('tab', { name: '통합 로그' })).toHaveAttribute('aria-selected', 'true');
  await user.click(screen.getByRole('treeitem', { name: 'api 상세' }));
  expect(screen.getByRole('tab', { name: '이력' })).toHaveAttribute('aria-selected', 'true');
  mock.listContainers.mockResolvedValueOnce({ sessionId: 'one', generation: 2, containers: rows.filter(item => item.name !== 'api'), refreshedAt: '2026-09-07T00:00:01Z', stale: false });
  await user.click(screen.getByRole('button', { name: '새로고침' }));
  await waitFor(() => expect(screen.getByRole('heading', { name: '프로젝트 · alpha' })).toBeVisible());
});
